SEED = 42
TRAIN_CSV = "data/train.csv"
TRAIN_TRAIN_CSV = "data/train.train.csv"
TRAIN_TEST_CSV = "data/train.test.csv"
TRAIN_RATIO = 0.8
NUM_LABELS = 3
MODEL_CHECKPOINT = "deepset/gbert-base"
OUTPUT_DIR = "models/" + MODEL_CHECKPOINT
BATCH_SIZE = 16
LEARNING_RATE = 2e-5
NB_EPOCH = 5
